development:
  adapter: mysql2
  encoding: utf8
  database: testapp_dev
  pool: 5
  username: root
  password: admin
test:
  adapter: mysql2
  encoding: utf8
  database: testapp_test
  pool: 5
  username: root
  password: admin
production:
  adapter: mysql2
  encoding: utf8
  database: testapp_production
  pool: 5
  username: root
  password: admin
